#!/usr/bin/env sh

cd /sys/class/backlight/amdgpu_bl*/

max=$(cat max_brightness)
current=$(cat brightness)

new="${1#+}"
new="${new#-}"
new="${new%%%}"
new="${new%x}"
new="${new:-$current}"

[ "$(printf %s "$1" | tail -c1)" = "%" ] && : $(( new = new * max / 100 ))
[ "$(printf %s "$1" | tail -c1)" = "x" ] && : $(( new = current * $new ))
[ "$(printf %s "$1" | head -c1)" = "+" ] && : $(( new = current + new ))
[ "$(printf %s "$1" | head -c1)" = "-" ] && : $(( new = current - new ))

echo "$current -> $new"

echo $(max 0 $(min $new $max)) > brightness

