#!/usr/bin/env zsh

monitors=("${(@f)$(hyprctl -j monitors all | jq -r '.[].name')}")
for monitor in $monitors; do
	files=(/Media/Wallpapers/OneDark/*(.)) && wallpaper $files[$((RANDOM % ${#files} + 1))] $monitor
done
