#!/usr/bin/env zsh

files=(/Media/Wallpapers/OneDark/*(.)) && wallpaper $files[$((RANDOM % ${#files} + 1))] eDP-1
files=(/Media/Wallpapers/OneDark/*(.)) && wallpaper $files[$((RANDOM % ${#files} + 1))] DP-1
